[package]
version = "1.2.3"
category = "Utility"
title = "VS Code integration"
description = "VS Code launcher and menu integration for Isaac Sim"
keywords = ["isaac", "python", "vscode", "editor"]
changelog = "docs/CHANGELOG.md"
readme = "docs/Overview.md"
preview_image = "data/preview.png"
icon = "data/icon.png"
writeTarget.kit = true

[dependencies]
"isaacsim.code_editor.python_server" = {}
"isaacsim.core.deprecation_manager" = {}
"omni.kit.notification_manager" = { optional = true }
"omni.kit.uiapp" = { optional = true }

[[python.module]]
name = "isaacsim.code_editor.vscode"

[documentation]
pages = ["docs/Overview.md",  "docs/CHANGELOG.md"]
