[package]
version = "0.3.0"
category = "other"
title = "Isaac Sim Robot Wizard [Deprecated]"
description = "Wizard to guide through robot import and configuration"
keywords = ["wizard","import"," "]
changelog = "docs/CHANGELOG.md"
readme = "docs/Overview.md"
preview_image = "data/preview.png"
icon = "data/icon.png"
writeTarget.kit = true

[deprecation]
warning = "Extension deprecated since Isaac Sim 6.0.0. No replacement."

[dependencies]
"isaacsim.core.deprecation_manager" = {}
"isaacsim.core.experimental.objects" = {}
"isaacsim.gui.components" = {}
"isaacsim.robot.schema" = {}

[[python.module]]
name = "isaacsim.robot_setup.wizard"

[settings]
# Timeout for resolving the robot wizard settings.
exts."isaacsim.robot_setup.wizard".timeout = 5

# Launch on startup.
persistent.exts."isaacsim.robot_setup.wizard".launch_on_startup = false

[[test]]
name = "startup"
enabled = true

[documentation]
pages = ["docs/Overview.md","docs/SETTINGS.md", "docs/CHANGELOG.md"]
