########################################################################################################################
# Example:
########################################################################################################################

#
# [[dependency]]                           # Toml way to define array of objects.
# python = "../_build/target-deps/python"  # Path to python used to install. Absolute or relative to this config.
# packages = ["numpy==1.23.5"]                     # Array of packages to install, they all will be passed directly to pip.
# target = "../_build/target-deps/numpy"   # Folder to install into.   Absolute or relative to this config.
# platforms = ["windows-x86_64"]           # Platform(s) to filter, default is ["*"].
# download_only = true                     # Do pip download instead of install, gets a whl file that can be installed later.

# !!!
# IMPORTANT: If you change this config cleanup target folder. Script check that it already exists and does nothing.


# Options. 
# Various options are available that are passed through pip during the installation.

# download_only: Only download the pip package, do not install it.
# install_dependencies: When set to False, dependencies of a pip package will not be downloaded or installed
# append_to_install_folder: When set to true and the target directory already exists, these packages will be appended to the existing folder.
# build_isolated: Sets `--isolated` for pip install when installing. This means that environment variables and user settings will be ignored.
# add_python_to_lib_path: Will set --global-options to include Python's lib and include folders when running the pip install. 
#    Useful when a python pip package has a C extension that needs to bind to Python. Setting this to true will set build_isolated to False.

########################################################################################################################
# Dependencies:
########################################################################################################################

# For newer version of pip we bundle only wheel files, to be installed at runtime upon first usage. 
# Disabled because we get this with the base omni.kit.pip_archive extension
# [[dependency]]
# python = "../_build/target-deps/python"
# packages = ["pip==21.2.4"]
# target = "../_build/target-deps/pip_archive"
# platforms = ["*-x86_64"]
# download_only = true

# For many other pip packages used by default we install them in `pip_prebundle` folder to make available without need to install immediately.

# NOTE - For any new packages added to this list, please make sure that the license is compatible with Omniverse (i.e. avoid GPL/LGPL) and
# that a SWIPAT bug report is filed for legal to validate if there is no existing ticket.
# The SWIPAT template is here: http://nvbugs/2732212
# Dependencies for aiohttp should not be installed by default as we do not want to pull in chardet due to its license. Use cchardet instead

# Target kit 109.x 
[[dependency]]
python = "../_build/target-deps/python"
packages = [
    # packages
    "torch==2.11.0+cu128",        # SWIPAT filed under: https://nvbugs/3682155 # Used by: isaacsim.core.simulation_manager, isaacsim.core.utils
    "torchvision==0.26.0+cu128", # SWIPAT filed under: https://nvbugs/3433812 # Used by: (none found)
    "torchaudio==2.11.0+cu128",   # SWIPAT filed under: https://nvbugs/5326960 # Used by: (none found)

    # dependencies
    "filelock==3.25.2",          # SWIPAT filed under: https://nvbugs/5303100 # Used by: (dependency of torch)
    "fsspec==2026.2.0",          # SWIPAT filed under: https://nvbugs/5303035 # Used by: (dependency of torch)
    "mpmath==1.3.0",             # SWIPAT filed under: https://nvbugs/5303037 # Used by: (dependency of sympy)
    "networkx==3.6.1",             # SWIPAT filed under: https://nvbugs/5303034 # Used by: (dependency of torch)
    "sympy==1.14.0",             # SWIPAT filed under: https://nvbugs/5303081 # Used by: (dependency of torch)
]
extra_args = ["--extra-index-url", "https://download.pytorch.org/whl/cu128"]
target = "../_build/target-deps/isaac_ml_prebundle"
platforms = ["*-x86_64"]
download_only = false
append_to_install_folder = true
gather_licenses_path = "../_build/PACKAGE-LICENSES/PIP-prebundled-LICENSES.txt"
install_dependencies = false

[[dependency]]
python = "../_build/target-deps/python"
packages = [
    # packages -- vision and audio do not have +cu128 versions
    "torch==2.11.0+cu128",  # SWIPAT filed under: https://nvbugs/3682155 # Used by: isaacsim.core.simulation_manager, isaacsim.core.utils
    "torchvision==0.26.0+cu128", # SWIPAT filed under: https://nvbugs/3433812 # Used by: (none found)
    "torchaudio==2.11.0+cu128", # SWIPAT filed under: https://nvbugs/5326960 # Used by: (none found)

    # dependencies
    "filelock==3.25.2", # SWIPAT filed under: https://nvbugs/5303100 # Used by: (dependency of torch)
    "fsspec==2026.2.0", # SWIPAT filed under: https://nvbugs/5303035 # Used by: (dependency of torch)
    "mpmath==1.3.0", # SWIPAT filed under: https://nvbugs/5303037 # Used by: (dependency of sympy)
    "networkx==3.6.1", # SWIPAT filed under: https://nvbugs/5303034 # Used by: (dependency of torch)
    "sympy==1.14.0", # SWIPAT filed under: https://nvbugs/5303081 # Used by: (dependency of torch)
]
extra_args = ["--extra-index-url", "https://download.pytorch.org/whl/cu128"]
target = "../_build/target-deps/isaac_ml_prebundle"
platforms = ["*-aarch64"]
download_only = false
append_to_install_folder = true
gather_licenses_path = "../_build/PACKAGE-LICENSES/PIP-prebundled-LICENSES.txt"
install_dependencies = false


# Windows torch does not need these so split them out. 
[[dependency]]
python = "../_build/target-deps/python"
packages = [
    "cuda-bindings==12.9.4",              # SWIPAT filed under: NA # Used by: (dependency of torch)
    "nvidia-cublas-cu12==12.8.4.1",       # SWIPAT filed under: NA # Used by: (dependency of nvidia-cudnn-cu12, nvidia-cusolver-cu12, torch)
    "nvidia-cuda-cupti-cu12==12.8.90",    # SWIPAT filed under: NA # Used by: (dependency of torch)
    "nvidia-cuda-nvrtc-cu12==12.8.93",    # SWIPAT filed under: NA # Used by: (dependency of torch)
    "nvidia-cuda-runtime-cu12==12.8.90",  # SWIPAT filed under: NA # Used by: (dependency of torch)
    "nvidia-cudnn-cu12==9.19.0.56",       # SWIPAT filed under: NA # Used by: (dependency of torch)
    "nvidia-cufft-cu12==11.3.3.83",       # SWIPAT filed under: NA # Used by: (dependency of torch)
    "nvidia-cufile-cu12==1.13.1.3",       # SWIPAT filed under: NA # Used by: (dependency of torch)
    "nvidia-curand-cu12==10.3.9.90",      # SWIPAT filed under: NA # Used by: (dependency of torch)
    "nvidia-cusolver-cu12==11.7.3.90",    # SWIPAT filed under: NA # Used by: (dependency of torch)
    "nvidia-cusparse-cu12==12.5.8.93",    # SWIPAT filed under: NA # Used by: (dependency of nvidia-cusolver-cu12, torch)
    "nvidia-cusparselt-cu12==0.7.1",      # SWIPAT filed under: NA # Used by: (dependency of torch)
    "nvidia-nccl-cu12==2.28.9",           # SWIPAT filed under: NA # Used by: (dependency of torch)
    "nvidia-nvjitlink-cu12==12.8.93",     # SWIPAT filed under: NA # Used by: (dependency of nvidia-cufft-cu12, nvidia-cusolver-cu12, nvidia-cusparse-cu12, torch)
    "nvidia-nvshmem-cu12==3.4.5",         # SWIPAT filed under: NA # Used by: (dependency of torch)
    "nvidia-nvtx-cu12==12.8.90",          # SWIPAT filed under: NA # Used by: (dependency of torch)
]
extra_args = ["--extra-index-url", "https://download.pytorch.org/whl/cu128"]
target = "../_build/target-deps/isaac_ml_prebundle"
platforms = ["linux-x86_64", "linux-aarch64"]
download_only = false
append_to_install_folder = true
gather_licenses_path = "../_build/PACKAGE-LICENSES/PIP-prebundled-LICENSES.txt"
install_dependencies = false
