[core]
# Load as early as possible
order = -1000
reloadable = false

[package]
version = "0.6.0"
category = "Internal"
title = "Newton Physics Pip Archive"
description = "Pip packages for the Newton physics engine"
keywords = ["isaac", "pip", "newton"]
changelog = "docs/CHANGELOG.md"
readme = "docs/Overview.md"
preview_image = "data/preview.png"
icon = "data/icon.png"
writeTarget.kit = true
writeTarget.platform = true # pip prebundle makes this extension os specific
writeTarget.python = true

[dependencies]
"omni.kit.pip_archive" = {} # import the base kit python archive

[[python.module]]
path = "pip_prebundle"

# That is empty module, added here only to make tests discoverable in test run
[[python.module]]
name = "isaacsim.pip.newton"

[[test]]
dependencies = [
    "omni.warp.core"
]